from bfgs import Bfgs
from cg import ConjugateGradient
from gd import GradientDescent
from hf import HessianFree
from ksd import KrylovSubspaceDescent
from lbfgs import Lbfgs
from ncg import NonlinearConjugateGradient
from nes import Xnes
from rmsprop import RmsProp
from rprop import Rprop
from sbfgs import Sbfgs
from smd import Smd
from nesterov import Nesterov
from asgd import Asgd
from tonga import tonga
from nn import NaturalNewton
from nn_lowrank import NaturalNewtonLR
