from bayesian import Bayesian
from bfgs import Bfgs
from cg import ConjugateGradient
from gd import GradientDescent
from ksd import KrylovSubspaceDescent
from lbfgs import Lbfgs
from ncg import NonlinearConjugateGradient
from nes import Xnes
from rprop import Rprop
from sbfgs import Sbfgs
